///GENERATED CODE - DO NOT MODIFY BY HAND'
///Generated by shared_pref_builder'

import 'package:shared_pref_annotation/shared_pref_annotation.dart';
import 'package:shared_preferences/shared_preferences.dart';

extension AppPrefSpExt on SharedPreferences {
  SPValue<String> get token => SPValue<String>(
      key: 'token', getter: getString, setter: setString, remover: remove);

  SPValue<String> get loginCode => SPValue<String>(
      key: 'loginCode', getter: getString, setter: setString, remover: remove);

  SPValue<String> get password => SPValue<String>(
      key: 'password', getter: getString, setter: setString, remover: remove);

  Set<SPValueBase> get entries => {token, loginCode, password};
}


